### ISSUE TITLE
Responsive Captivate Theme - Search Bug

### ISSUE THREAD

**Issue by SpiritWolfie** [SpiritWolfie/Social-Engine-Addons#1]
When searching for things on this theme, sometimes certain things break's the css or style sheet...

A Example would be 
 - https://www.furgather.net/search?query=babyfurs&type=&submit= 
This loads fine however if you search
- https://www.furgather.net/search?query=babyfur&type=&submit=
The style sheet/css breaks, the only differance in this search string is the (s) at the end of what we searched, This happens allot in other cases as welll.

I have tested this on a fresh install of Social engine and their demo site and this does not happen, so I firmly believe its a bug with a plugin.

**Comment by socialengineaddons** [comment]
We are working on this along with our developer.

**Comment by socialengineaddons** [comment]
The below FTP details are not working for us now.Please send us the updated details.

Host - fluffywaddles.net
username - darkfg
password - Gy5xo7!5

**Comment by SpiritWolfie** [comment]
I've merged fluffywaddles with Furgather so please don't worry about that
anymore, figured managing two websites was pointless when they both do the
same thing.

This issue exists in Furgather as well.

**Comment by SpiritWolfie** [comment]
@socialengineaddons Do not put FTP info on a public github, are you trying to compromise my server box's security?

Secondly, these are reports for Furgather....

**Comment by socialengineaddons** [comment]
We have resolved this issue on your website. We have sent the change done in the ticket: https://www.socialengineaddons.com/support/viewthread/42657

**Comment by SpiritWolfie** [comment]
Confirmed this has been resolved, will close ticket
