### ISSUE TITLE
Responsive Captivate Theme - Landing page CSS overlap

### ISSUE THREAD

**Issue by SpiritWolfie** [SpiritWolfie/Social-Engine-Addons#3]
On the landing page image (used in the image rotater or static image) over laps the theme of the website, this creates css issues

Please see the following pictures for a example

This is a picture of the landing page as is
![image](https://cloud.githubusercontent.com/assets/9712738/23731345/dad3f5fc-0421-11e7-936a-e83a41a314f0.png)

This is a picture of the CSS element 
![image](https://cloud.githubusercontent.com/assets/9712738/23731374/0ae90d0e-0422-11e7-985f-86f110cb0e3a.png)

if you delete said Element from your browser under inspect you get this
![image](https://cloud.githubusercontent.com/assets/9712738/23731382/211a1f00-0422-11e7-9b11-b7f185759470.png)

The landing page itself should act as a dedicated page and have no baring on the theme used once logged in. Landing theme and /home/ and such should be able to be different without CSS conflict.

**Comment by socialengineaddons** [comment]
We have got your point here. We need to disucss this with our UI developer once. We will get back to you with an update soon.

**Comment by socialengineaddons** [comment]
To resolve this issue, we will need to remove 'body background image'. But, if we will remove this body background image then, it will get removed from the whole website. Please let us know your views here.

**Comment by SpiritWolfie** [comment]
@socialengineaddons That does not resolve the issue... A landing page is suppose to be Static, you know a Landing page?

if its affecting the rest of the site then something is not coded correctly here on ether the addons side or social engines side, a Landing page should be its own page for a reason, it shouldn't be pulling elements from the rest of the site... So removing our theme would not resolve this issue it'd only make it worse....

is this a issue with the addon or social engine itself so I can file a bug report with the correct source?

**Comment by socialengineaddons** [comment]
We have resolved this issue on your website. For this, we have added code in customization.css: https://www.furgather.net/admin/themes?file=customization.css

Added below code:
body#global_page_core-index-index{background-image: none !important;}

Please recheck at your end once.

**Comment by SpiritWolfie** [comment]
@socialengineaddons seems this has been resolved, thank you

Could you look at - https://github.com/SpiritWolfie/Social-Engine-Addons/issues/8
